/* tslint:disable */
/* eslint-disable */

/* auto-generated by NAPI-RS */

export interface KeyStats {
  totalKeystrokes: number
  keyFrequencies: Record<string, number>
  startTime: number
  lastKeystrokeTime: number
}
export declare class KeystrokeCounter {
  constructor()
  startTracking(): void
  stopTracking(): void
  getTotalKeystrokes(): number
  getStats(): KeyStats
  resetStats(): void
}
